# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: fc660c
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME='"H6 Steel"'
    artifact-name: fc660c_h6_steel
  #  - board: fc660c
  #    snippet: enable_ec_calibrator
  #    artifact-name: fc660c_calibrator
  - board: fc660c
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME='"FC660C Debug"'
    artifact-name: fc660c_usb-logging
